# Request this on site.usegalaxy.org.au with:
# https://site.usegalaxy.org.au/lab/export?content_root=https://github.com/galaxyproject/galaxy_codex/blob/main/subdomains/genome/base.yml

# Check out the documentation for building exported labs:
# https://site.usegalaxy.org.au/lab/export

# Use these variables in HTML templates like:
# "Welcome to the Galaxy {{ site_name }} {{ lab_name }}"
# To make the content more generic and reusable across sites
site_name: ""
lab_name: Genome Lab
nationality: ""
galaxy_base_url: https://genome.usegalaxy.org  # Use for rendering tool/workflow URLs. Trailing '/' will be removed.
subdomain: genome
root_domain: usegalaxy.org

support_url: https://help.usegalaxy.org
terms_url: https://usegalaxy.org/static/terms.html
data_policy_url: https://usegalaxy.org/static/terms.html
# tool_request_url:
# quota_request_url:

# feedback_email: help@mygalaxy.org  # set to enable feedback form

# Custom content relative to this file URL
header_logo: static/logo.png
custom_css: static/custom.css
intro_md: templates/intro.html
conclusion_md: templates/conclusion.html
footer_md: templates/footer.html


# Data (Tools, Workflows etc.) to be rendered into sections/tabs/accordion elements.
# Either:
#   1. Relative to this file URL
#   2. Full URL to fetch content from a different remote location
sections:
  - data.yml
  - assembly.yml
  - annotation.yml
