# Request this as a webpage with:
# https://site.usegalaxy.org.au/lab/export?content_root=https://raw.githubusercontent.com/nomadscientist/galaxy_codex/subdomain_unification/subdomains/singlecell/base.yml

# -----------------------------------------------------------------------------
# Use these variables in HTML templates like:
# "Welcome to the Galaxy {{ site_name }} {{ lab_name }}"
# To make the content more generic and reusable across sites

# These will be rendered like "Welcome to the Galaxy {{ site_name }} {{ lab_name }}!"
site_name: Australia
lab_name: microGalaxy Lab
analysis_name: microGalaxy
nationality: Australian

# Used for rendering tool/workflow links. Trailing '/' will be removed.
galaxy_base_url: https://singlecell.usegalaxy.org
subdomain: singlecell
root_domain: usegalaxy.org

# This will enable a feedback form on the webpage:
# feedback_email: help@mygalaxy.org

support_url: https://help.galaxyproject.org
# quota_request_url: https://help.galaxyproject.org
data_policy_url: https://usegalaxy.org/static/terms.html
terms_url: https://usegalaxy.org/static/terms.html

help_links:
  - title: General Galaxy support
    url: https://galaxyproject.org/support/
  - title: Single Cell help forum
    url: https://help.galaxyproject.org/tag/single-cell
  - title: General Galaxy help forum
    url: https://help.galaxyproject.org
  - title: Galaxy Training Network Slack workspace
    url: https://join.slack.com/t/gtnsmrgsbord/shared_invite/zt-2llyx6p8j-LmpEIsJu0t4MQkBctkN8qg
  - title: Single cell Slack channel (#single-cell-users)
    url: https://gtnsmrgsbord.slack.com/archives/C06PBRR40D7
  - title: Single cell user community chat room (Same channel but using Matrix/Element)
    url: https://matrix.to/#/#Galaxy-Training-Network_galaxy-single-cell:gitter.im
  - title: Galaxy Training Community chat
    url: https://matrix.to/#/#Galaxy-Training-Network_Lobby:gitter.im
  - title: Usegalaxy.org chat
    url: https://matrix.to/#/#galaxyproject_Lobby:gitter.im

intro_extra_md: ""
conclusion_extra_md: ""

# -----------------------------------------------------------------------------
# Custom content relative to this file URL

header_logo: static/logo_single_cell.svg
custom_css: static/custom.css
intro_md: templates/intro.html
conclusion_md: templates/conclusion.html
footer_md: templates/footer.html


# Data (Tools, Workflows etc.) to be rendered into sections/tabs/accordion elements.
# Either:
#   1. Relative to this file URL
#   2. Full URL to fetch globally centralized content
sections:
  - sections/1_beginner.yml
  - sections/3_advanced.yml
  - sections/4_community.yml
  # - sections/5_tools.yml

# -----------------------------------------------------------------------------
