name: Weekly resource fetching

on:
  workflow_dispatch:
    push:
      branches:
        - 'main'
        - 'token_fix_automerge'
  schedule:
    #Every Sunday at 8:00 am
    - cron: "0 8 * * 0" 

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "tools"
  cancel-in-progress: false

jobs:
  fetch-workflows:
    runs-on: ubuntu-latest
    name: Fetch workflows
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install requirement
        run: |
          python -m pip install -r requirements.txt
          sudo apt-get install jq
      - name: Fetch all workflows
        run: | 
          bash sources/bin/extract_all_workflows.sh 
        env: 
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_TOKEN }}
      - name: Archive tutorials artifacts
        uses: actions/upload-artifact@v7
        with:
          name: workflows
          path: communities/all/resources/workflows.json
#  fetch-citations:
#    runs-on: ubuntu-latest
#    name: Fetch citations
#    steps:
#      - name: Checkout main
#        uses: actions/checkout@v6
#      - uses: actions/setup-python@v6
#        with:
#          python-version: '3.11'
#      - name: Install requirement
#        run: |
#          python -m pip install -r requirements.txt
#          sudo apt-get install jq
#      - name: Fetch all citations
#        run: | 
#          bash sources/bin/extract_all_citations.sh
#      - name: Archive citations artifacts
#        uses: actions/upload-artifact@v7
#        with:
#          name: workflows
#          path: communities/all/resources/citations.json
  merge-fetch:
    runs-on: ubuntu-latest
    needs: 
      - fetch-workflows
#      - fetch-citations
    name: Merge tools and push changes
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
          with:
            # We pass the "PAT" secret to the checkout action; if no PAT secret is available to the workflow runner (eg. Dependabot) we fall back to the default "GITHUB_TOKEN".
            token: ${{ secrets.PAT || secrets.GH_ACTIONS_PAT }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install requirement
        run: |
          python -m pip install -r requirements.txt
          sudo apt-get install jq
      - name: Download workflows
        uses: actions/download-artifact@v8
        with:
          pattern: workflows
          merge-multiple: true
          path: communities/all/resources/
      - name: Display structure of downloaded files
        run: ls -R communities/all/resources/
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update resources"
          branch: main
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          repository_initial_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
