name: Populate labs

on:
  workflow_dispatch:
#  push:
#  pull_request:
#    branches:
#      - main
#    paths:
#      - 'sources/bin/**'

jobs:
  populate_labs:
    runs-on: ubuntu-latest
    name: populate_labs
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirement
        run: |
          python -m pip install -r requirements.txt
          sudo apt-get install jq
      - name: Populate microGalaxy Lab
        run: | 
          bash sources/bin/populate_labs.sh
        env: 
          COMMUNITY: microgalaxy
      - name: Populate biodiversity Lab
        run: | 
          bash sources/bin/populate_labs.sh
        env: 
          COMMUNITY: biodiversity
      - name: Creat web page labs
        run: | 
          bash sources/bin/lab_creation.sh
#      - name: Populate labs with tuto
#        run: | 
#          python sources/bin/populate_labs_tutorials.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update resources
          title: Populate labs
          body: Populate labs done via GitHub Action
          base: main
          branch: populate-labs
          delete-branch: true
