name: Run tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'  # This will trigger the workflow only if files in the 'bin' folder are modified.

jobs:
  unittest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Run unittests
        run: |
          PYTHONPATH=bin python -m unittest discover -s bin/tests
