name: Utilities
on:
  workflow_dispatch:
  schedule:
    #Every Sunday at 7:00 am
    - cron: "0 7 * * 0" 

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "tools"
  cancel-in-progress: false
  
permissions:
  contents: write

jobs:
    fetch-available-servers:
      runs-on: ubuntu-20.04
      name: Fetch list of all available servers
      steps:
        - name: Checkout main
          uses: actions/checkout@v4
          with:
            ref: main #pull latest code produced by job 1, not the revision that started the workflow (https://github.com/actions/checkout/issues/439)
        - name: Checkout results
          uses: actions/checkout@v4
          with:
            ref: results
            path: results
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install requirement
          run: python -m pip install -r requirements.txt
        - name: Run script 
          run: | 
            python bin/get_public_galaxy_servers.py -o results/available_public_servers.csv
        - name: Commit servers 
          uses: s0/git-publish-subdir-action@develop
          env:
            BRANCH: results
            FOLDER: results
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO: self
            SKIP_EMPTY_COMMITS: true